; Generated by simplesc - SIMPLES to NASM compiler
; Program: Soma

section .data
    newline db 10
    minus_sign db '-', 0

section .bss
    buffer resb 16
    input_buffer resb 16


section .text
    global _start

_start:
    mov ebp, esp
    sub esp, 0
    and esp, -16
    mov eax, 3
    mov ebx, 0
    mov ecx, input_buffer
    mov edx, 16
    int 0x80
    xor eax, eax
    xor ebx, ebx
    mov esi, input_buffer
.conv_-4:
    movzx ecx, byte [esi]
    cmp ecx, 10
    je .done_-4
    cmp ecx, 0
    je .done_-4
    sub ecx, '0'
    imul eax, eax, 10
    add eax, ecx
    inc esi
    jmp .conv_-4
.done_-4:
    mov [ebp-4], eax
    mov eax, 3
    mov ebx, 0
    mov ecx, input_buffer
    mov edx, 16
    int 0x80
    xor eax, eax
    xor ebx, ebx
    mov esi, input_buffer
.conv_-8:
    movzx ecx, byte [esi]
    cmp ecx, 10
    je .done_-8
    cmp ecx, 0
    je .done_-8
    sub ecx, '0'
    imul eax, eax, 10
    add eax, ecx
    inc esi
    jmp .conv_-8
.done_-8:
    mov [ebp-8], eax
    xor eax, eax
    push eax
    xor eax, eax
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp-12]
    test eax, eax
    jns .pos
    push eax
    mov eax, 4
    mov ebx, 1
    mov ecx, minus_sign
    mov edx, 1
    int 0x80
    pop eax
    neg eax
.pos:
    xor ecx, ecx
    mov ebx, 10
.div:
    xor edx, edx
    div ebx
    push edx
    inc ecx
    test eax, eax
    jnz .div
.wloop:
    pop eax
    add eax, '0'
    push ecx
    mov [buffer], eax
    mov eax, 4
    mov ebx, 1
    mov ecx, buffer
    mov edx, 1
    int 0x80
    pop ecx
    dec ecx
    test ecx, ecx
    jnz .wloop
    mov eax, 1
    xor ebx, ebx
    int 0x80
